name: JackyStjames
favicon: null
layout_spectrum: 0.60112
typography_spectrum: 0.41576
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede4df'
    - '#172f31'
    - '#866243'
    - '#c2a07b'
    - '#ae8359'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
