name: JackyStjames
favicon: null
layout_spectrum: 0.4296435557771474
typography_spectrum: 0.08242995385080576
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.32626206311397254
  lightness: 0.5557841518893838
  saturation: 0.692140691448003
  rhythmicContrast: 0.6049120044335723
purpose: []
