name: JackyStjames
favicon: null
layout_spectrum: 0.17574
typography_spectrum: 0.55642
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4e5'
    - '#7a4d38'
    - '#912024'
    - '#e0b52a'
    - '#100204'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
