name: JackyStjames
favicon: null
layout_spectrum: 0.2675
typography_spectrum: 0.25782
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5c9bb'
    - '#a29b88'
    - '#46382f'
    - '#7d6c58'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
