name: JackyStjames
favicon: null
layout_spectrum: 0.17574
typography_spectrum: 0.55642
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a09'
    - '#362c20'
    - '#afa999'
    - '#656253'
    - '#c8c7b5'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
