name: JackyStjames
favicon: null
layout_spectrum: 0.74177
typography_spectrum: 0.41576
title: Jacky St. James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8a387'
    - '#b87051'
    - '#21140f'
    - '#764d31'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
